// <auto-generated />
namespace ECBack.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modifythestructureofordersaleandaddamidtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifythestructureofordersaleandaddamidtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201807231519321_modify the structure of ordersale and add a mid table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
