// <auto-generated />
namespace ECBack.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatethetableofquestionandattrbutes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatethetableofquestionandattrbutes));
        
        string IMigrationMetadata.Id
        {
            get { return "201807240812090_update the table of question and attrbutes."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
