// <auto-generated />
namespace ECBack.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeschemaofprog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeschemaofprog));
        
        string IMigrationMetadata.Id
        {
            get { return "201807241733414_change schema of prog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
