// <auto-generated />
namespace ECBack.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modifymodelsforuserandsoon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifymodelsforuserandsoon));
        
        string IMigrationMetadata.Id
        {
            get { return "201807161833498_modify models for user and so on."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
